### ISSUE TITLE
Error in passenger, newobj hooks is already disabled

### ISSUE THREAD

**Issue by nouse** [ko1/allocation_tracer#14]
Environment:
ruby 2.3.3 passenger 5.1.2

Error message:

> App 21967 stderr: [ 2017-04-06 02:42:26.3039 21986/0x00000001949020(Worker 1) utils.rb:87 ]: *** Exception RuntimeError in Rack application object (newobj hooks is already disabled.) (process 21986, thread 0x00000001949020(Worker 1)):
> App 21967 stderr:       from /usr/lib/gems/allocation_tracer-0.6.3/lib/rack/allocation_tracer.rb:85:in `result'
> App 21967 stderr:       from /usr/lib/gems/allocation_tracer-0.6.3/lib/rack/allocation_tracer.rb:85:in `call'
> App 21967 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
> App 21967 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
> App 21967 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
> App 21967 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
> App 21967 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by ko1** [comment]
Sorry I have no idea why.

**Comment by nouse** [comment]
Then can I recover from this error, by enable newobj hooks manually?

**Comment by ko1** [comment]
It can.
Do you stop hooks before this error?

**Comment by nouse** [comment]
No, it may be stopped at last successful access to /allocation_tracer/.
